# Copyright © 2023 Stephan Kunz
# See https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver="2"

members = [
	"dimas",
	"examples/liveliness",
	"examples/pingpong",
	"examples/pubsub",
	"examples/queries",
]

[workspace.lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"
#unused="allow" # for dev only

[workspace.lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"

[workspace.package]
rust-version = "1.75.0"
edition = "2021"
version = "0.0.7"
authors = [
	"stepkun <stephan.kunz@kabelbw.de>",
]
#license = "NGMC"
license-file = "LICENSE"
keywords = ["automation", "mas", "robot", "robotics"]
categories = [
	"development-tools",
	"science::robotics",
	"simulation"
]

[workspace.dependencies]
bitcode = "0.6.0-beta.1"
dimas = { path = "dimas" }
dirs = "5"
json5 = "0.4"
serde = { version = "1", default-features = false, features = ["derive"] }
thiserror = "1"
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
#zenoh = { version = "0.10.1-rc", features = ["unstable"] } # "shared-memory" ,"transport_unixpipe",
zenoh = { git = "https://github.com/eclipse-zenoh/zenoh", rev = "ba50eec2", features = ["unstable"]}
#zenoh = { git = "https://github.com/eclipse-zenoh/zenoh", branch = "main", features = ["unstable"]}

[profile.release]
opt-level = 'z'   # Optimize for size.
lto = true        # Enable Link Time Optimisation
codegen-units = 1 # Reduced to increase optimisations.
#panic = 'abort'   # Abort on panic
strip = "symbols" # Strip symbols from binary
