# See https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver="2"

members = [
	"dimas",
	"dimasctl",
	"dimasmon",
	"examples/nemo",
]

[lints.rust]
unsafe_code="forbid"
#unused="allow" # for dev only

[workspace.package]
rust-version = "1.75.0"
version = "0.0.1"
edition = "2021"
authors = [
	"stepkun stephan.kunz@kabelbw.de",
]
license-file = "LICENSE"

[workspace.dependencies]
#async-std = { version = "1", features = ["unstable", "attributes", "tokio1",] }
#anyhow = "1"
#bincode = { git = "https://github.com/bincode-org/bincode", branch = "trunk" }
clap = { version = "4", features = ["derive"] }
default-net = "0.21"
dimas = { path = "dimas" }
#derive_more = { version = "0.99", features = ["from", "display", "deref",] }
#makepad-widgets = { path = "../makepad/widgets" }
#makepad-widgets = "0.6"
serde = { version = "1", features = ["derive"] }
#serde_derive = "1"
serde_json = "1"
#serial_test  = "2"
sysinfo = "0.30"
#thiserror = "1"
tokio = { version = "1", features = ["full"] }
#zenoh = { path = "../zenoh/zenoh", features = ["unstable"] }
zenoh = { version = "0.10.1-rc", features = ["unstable"] }
