# Copyright © 2023 Stephan Kunz
# See https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
resolver="2"

members = [
	"dimas",
	"examples/liveliness",
	"examples/pubsub",
	"examples/queries",
]

[workspace.lints.rust]
unsafe_code="forbid"
unused="allow" # for dev only

[workspace.package]
rust-version = "1.75.0"
edition = "2021"
version = "0.0.1"
authors = [
	"stepkun stephan.kunz@kabelbw.de",
]
license-file = "LICENSE"

[workspace.dependencies]
chrono = { version = "^0.4", features = ["serde"] }
clap = { version = "^4.0", features = ["derive"] }
dimas = { path = "dimas" }
#derive_more = { version = "^0.99", features = ["from", "display", "deref",] }
derive_more = "^0.99"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
#tokio = { version = "^1.0", features = ["full"] }
tokio = "^1.0"
#zenoh = { path = "../zenoh/zenoh", features = ["unstable"] }
zenoh = { version = "0.10.1-rc", features = ["unstable"] }
