[package]
name = "dimas-commands"
rust-version.workspace = true
edition.workspace = true
version.workspace = true
authors.workspace = true
license-file.workspace = true
keywords.workspace = true
categories.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
derivative = { workspace = true }
dimas-com = { workspace = true }
dimas-config = { workspace = true }
itertools = { workspace = true }
tracing = { workspace = true}
zenoh = { workspace = true }
