# Copyright © 2023 Stephan Kunz
[package]
name = "queries"
rust-version = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
publish = false
license-file = { workspace = true }
description = "Queryable/Query example"

[lints]
workspace = true

[[bin]]
name = "queryable"
path = "src/queryable.rs"

[[bin]]
name = "query"
path = "src/query.rs"

[dependencies]
clap = { workspace = true }
dimas = { workspace = true }
tokio = { workspace = true }
zenoh = { workspace = true }

[dev-dependencies]
