
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.embark-studios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.fermyon]
url = "https://raw.githubusercontent.com/fermyon/spin/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[policy.dimas]
audit-as-crates-io = true

[policy.dimas-com]
audit-as-crates-io = true

[policy.dimas-commands]
audit-as-crates-io = true

[policy.dimas-config]
audit-as-crates-io = true

[policy.dimas-core]
audit-as-crates-io = true

[policy.dimasmon]
audit-as-crates-io = true

[[exemptions.aes]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.ahash]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.base64ct]]
version = "1.6.0"
criteria = "safe-to-deploy"

[[exemptions.chrono]]
version = "0.4.34"
criteria = "safe-to-deploy"

[[exemptions.concurrent-queue]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.const-oid]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.const_format]]
version = "0.2.32"
criteria = "safe-to-deploy"

[[exemptions.const_format_proc_macros]]
version = "0.2.32"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.crossbeam-utils]]
version = "0.8.19"
criteria = "safe-to-deploy"

[[exemptions.data-encoding]]
version = "2.5.0"
criteria = "safe-to-deploy"

[[exemptions.der]]
version = "0.7.8"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dimas]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.dirs]]
version = "5.0.1"
criteria = "safe-to-deploy"

[[exemptions.dirs-sys]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "2.5.3"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "4.0.3"
criteria = "safe-to-deploy"

[[exemptions.event-listener]]
version = "5.2.0"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.flume]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.30"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.2.12"
criteria = "safe-to-deploy"

[[exemptions.git-version]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.git-version-macro]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.humantime]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.ipnetwork]]
version = "0.20.0"
criteria = "safe-to-deploy"

[[exemptions.json5]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.keccak]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.keyed-set]]
version = "0.4.5"
criteria = "safe-to-deploy"

[[exemptions.libloading]]
version = "0.8.2"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.0.1"
criteria = "safe-to-deploy"

[[exemptions.lz4_flex]]
version = "0.11.2"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "0.8.11"
criteria = "safe-to-deploy"

[[exemptions.nanorand]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.nix]]
version = "0.27.1"
criteria = "safe-to-deploy"

[[exemptions.no-std-net]]
version = "0.6.0"
criteria = "safe-to-deploy"

[[exemptions.num-bigint-dig]]
version = "0.8.4"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.19.0"
criteria = "safe-to-deploy"

[[exemptions.parking]]
version = "2.2.0"
criteria = "safe-to-deploy"

[[exemptions.pem-rfc7468]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.pest]]
version = "2.7.8"
criteria = "safe-to-deploy"

[[exemptions.pest_derive]]
version = "2.7.8"
criteria = "safe-to-deploy"

[[exemptions.pest_generator]]
version = "2.7.8"
criteria = "safe-to-deploy"

[[exemptions.pest_meta]]
version = "2.7.8"
criteria = "safe-to-deploy"

[[exemptions.petgraph]]
version = "0.6.4"
criteria = "safe-to-deploy"

[[exemptions.pkcs1]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.pkcs8]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.pnet_base]]
version = "0.34.0"
criteria = "safe-to-deploy"

[[exemptions.pnet_datalink]]
version = "0.34.0"
criteria = "safe-to-deploy"

[[exemptions.pnet_sys]]
version = "0.34.0"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.quinn]]
version = "0.10.2"
criteria = "safe-to-deploy"

[[exemptions.quinn-proto]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.redox_users]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.ring]]
version = "0.17.8"
criteria = "safe-to-deploy"

[[exemptions.ringbuffer-spsc]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.rsa]]
version = "0.9.6"
criteria = "safe-to-deploy"

[[exemptions.rustls]]
version = "0.21.10"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.rustls-native-certs]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "1.0.4"
criteria = "safe-to-deploy"

[[exemptions.rustls-pemfile]]
version = "2.1.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-pki-types]]
version = "1.3.1"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.101.7"
criteria = "safe-to-deploy"

[[exemptions.rustls-webpki]]
version = "0.102.2"
criteria = "safe-to-deploy"

[[exemptions.schannel]]
version = "0.1.23"
criteria = "safe-to-deploy"

[[exemptions.schemars]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.schemars_derive]]
version = "0.8.16"
criteria = "safe-to-deploy"

[[exemptions.secrecy]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.security-framework]]
version = "2.9.2"
criteria = "safe-to-deploy"

[[exemptions.security-framework-sys]]
version = "2.9.1"
criteria = "safe-to-deploy"

[[exemptions.shellexpand]]
version = "3.1.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.6"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spki]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.token-cell]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.tokio-tungstenite]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.tungstenite]]
version = "0.20.1"
criteria = "safe-to-deploy"

[[exemptions.twox-hash]]
version = "1.6.3"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.17.0"
criteria = "safe-to-deploy"

[[exemptions.uhlc]]
version = "0.6.3"
criteria = "safe-to-deploy"

[[exemptions.untrusted]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.unzip-n]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.utf-8]]
version = "0.7.6"
criteria = "safe-to-deploy"

[[exemptions.uuid]]
version = "1.7.0"
criteria = "safe-to-deploy"

[[exemptions.validated_struct]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.validated_struct_macros]]
version = "2.1.0"
criteria = "safe-to-deploy"

[[exemptions.webpki-roots]]
version = "0.26.1"
criteria = "safe-to-deploy"

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.7.0"
criteria = "safe-to-deploy"
