[package]
name = "dimasctl"
rust-version = { workspace = true }
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
description = "Command Line Interface for DiMAS"

[dependencies]
clap = { workspace = true }
dimas = { workspace = true }
#thiserror = { workspace = true }
zenoh = { workspace = true }

[dev-dependencies]
#anyhow  = { workspace = true }
